# -------------------------------- App Config -------------------------------- #
server:
<<<<<<< HEAD
  Host: 0.0.0.0
  Port: 3000
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  JWTSecretKey: 95d1c361b680578a9a6e8aa4a4fcf3fe02484cbf7a38906258eaed13ac1ca4ce
=======
    Host: 0.0.0.0
    Port: 3000
    JWTSecretKey: 95d1c361b680578a9a6e8aa4a4fcf3fe02484cbf7a38906258eaed13ac1ca4ce
>>>>>>> b5db15a8bb084ecb08d3cfbd59e7d88d79375b51

# ------------------------------ Postgres Config ----------------------------- #
postgres:
    User: postgres
    Password: postgres
    Host: "127.0.0.1"
    Port: 5444
    NameDB: store_db

# ------------------------------- Minio Config ------------------------------- #
aws:
    Endpoint: localhost:9000
    MinioAccessKey: admin
    MinioSecretKet: WqYNmSnOBT
    UseSSL: false

redis:
    Host: localhost
    Port: 6379
    Password:
    Db: 0

mail:
    Host: smtp.gmail.com
    Port: 465
    User: txdgh12@gmail.com
    Password: nltxrgzbodwdewjp
# bucket:
#   MinioAvatarBucket: avatar-user-store
#   MinioProductBucket: product-store

<<<<<<< HEAD
# ------------------------------- Logger Config ------------------------------ #
logger:
  Level: trace # Required [trace, debug, info, warn, error, fatal, panic]
  Caller: true # Required [true, false]
  Encoding: text # Optional [json, text], default json
  Development: true
=======
>>>>>>> b5db15a8bb084ecb08d3cfbd59e7d88d79375b51
